print("BATALLA NAVAL")
print("Materiales Necesarios:")
print("Dos tableros de juego, cada uno con una cuadrícula de 10x10 casillas.")
print("Barcos que ocupan un cierto número de casillas en la cuadrícula.")
print("Objetivos:")
print("Hundir todos los barcos del oponente antes de que él hunda los tuyos.")
print("Preparación:")
print("1. Cada jugador coloca sus barcos en su tablero sin que el oponente pueda ver la disposición.")
print("Los barcos pueden colocarse horizontal o verticalmente en la cuadrícula, pero no pueden superponerse ni tocarse entre sí.")
print("Juego:")
print("1. Los jugadores se turnan para bombardear las casillas del oponente intentando descubrir la ubicación de los barcos.")
print("2. En cada turno, un jugador nombra una casilla en el tablero del oponente (por ejemplo, A3, E7) para intentar 'hundir' un barco.")
print("3. El oponente responde diciendo 'agua' si el disparo no golpea ningún barco, o 'tocado' si golpea un barco pero no lo hunde completamente.")
print("4. Cuando todos los cuadrados de un barco han sido alcanzados, se dice 'hundido' y el jugador marca todas las casillas del barco en su tablero.")
print("5. El primer jugador en hundir todos los barcos del oponente gana la partida.")
print("Estrategias:")
print("Los jugadores intentan deducir la ubicación de los barcos del oponente basándose en los resultados de sus disparos anteriores.")
print("Después de un 'tocado', los jugadores suelen disparar en las casillas adyacentes para intentar hundir completamente un barco.")
print("Mantén registro de los disparos y los resultados para planificar mejor tus siguientes movimientos.")